[package]
name = "sandbox-ipc"
version = "0.2.0"

description = "An IPC implementation with an eye toward enabling privilege separation."
repository = "https://github.com/JohnColanduoni/sandbox-ipc"
authors = ["john@colanduoni.com"]
license = "MIT OR Apache-2.0"

[dependencies]
log = ">=0.3"
uuid = { version = "0.5", features = ["v4", "serde"] }
rand = "0.3"
lazy_static = "0.2.9"

serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
bincode = "0.9"

futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["minwindef", "ntdef", "guiddef", "winsock2", "namedpipeapi", "ioapiset", "memoryapi", "sysinfoapi", "synchapi"] }
winhandle = "0.3"
widestring = "0.2"
mio-named-pipes = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
mio = "0.6"

[dev-dependencies]
serde_json = "1.0"

[[test]]
name = "child_channel"
harness = false

[[test]]
name = "named_channel"
harness = false

[[bench]]
name = "shm_queue"
harness = false
