[package]
name = "sandbox-ipc"
version = "0.1.1"

description = "An IPC implementation with an eye toward enabling privilege separation."
repository = "https://github.com/JohnColanduoni/sandbox-ipc"
authors = ["john@colanduoni.com"]
license = "MIT OR Apache-2.0"

[dependencies]
log = ">=0.3"
uuid = { version = "0.5", features = ["v4", "serde"] }
rand = "0.3"

serde = "1.0"
serde_derive = "1.0"
bincode = "0.9"

futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = ">=0.2"
kernel32-sys = ">=0.2"
advapi32-sys = ">=0.2"
winhandle = "0.1"
mio-named-pipes = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
mio = "0.6"

[dev-dependencies]
serde_json = "1.0"

[[test]]
name = "child_channel"
harness = false

[[test]]
name = "named_channel"
harness = false

[[bench]]
name = "shm_queue"
harness = false
